name:                fastcdc
version:             0.0.0
github:              "gkleen/fastcdc/fastcdc"
license:             BSD3
author:              "Gregor Kleen"
maintainer:          "aethoago@141.li"
copyright:           "2020 Gregor Kleen"

dependencies:
  - base >= 4.7 && < 5
  - gearhash >= 0.0 && < 1
  - conduit >= 1.3 && < 1.4
  - bytestring >= 0.10 && < 0.11
  - bv-little >= 1.1 && < 2

default-extensions:
  - NoImplicitPrelude

other-extensions:
  - BangPatterns
  - PatternGuards
  - RecordWildCards
  - ScopedTypeVariables
  - DeriveGeneric
  - DeriveDataTypeable

library:
  source-dirs: src
  exposed-modules:
    - Data.Conduit.Algorithms.FastCDC

executables:
  fastcdc:
    source-dirs: fastcdc
    main: Main.hs
    other-modules: []
    dependencies:
      - fastcdc
